import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./_components";
import localFont from "next/font/local";
import { Footer } from "./_components/footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const bwGradual = localFont({
    src: [
        {
            path: "../assets/fonts/BwGradual-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../assets/fonts/BwGradual-Medium.woff2",
            weight: "500",
            style: "normal",
        },
        {
            path: "../assets/fonts/BwGradual-Bold.woff2",
            weight: "700",
            style: "normal",
        },
    ],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={bwGradual.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
